anh_content_admin:
    path: /
    defaults: { _controller: AnhContentBundle:Admin:index }

anh_content_admin_category_list:
    path: /category-list
    defaults: { _controller: AnhContentBundle:Admin:categoryList }

anh_content_admin_category_add:
    path: /category-add
    defaults: { _controller: AnhContentBundle:Admin:categoryAdd }

anh_content_admin_category_edit:
    pattern: /category-edit-{id}
    defaults: { _controller: AnhContentBundle:Admin:categoryEdit }
    requirements:
        id: "\d+"

anh_content_admin_category_delete:
    path: /category-delete
    defaults: { _controller: AnhContentBundle:Admin:categoryDelete }
    methods: [ 'POST' ]

anh_content_admin_tag_list:
    pattern: /tag-list-{page}
    defaults: { _controller: AnhContentBundle:Admin:tagList, page: 1 }
    requirements:
        page: "\d+"

anh_content_admin_tag_edit:
    pattern: /tag-edit-{id}
    defaults: { _controller: AnhContentBundle:Admin:tagEdit }
    requirements:
        id: "\d+"

anh_content_admin_tag_delete:
    path: /tag-delete
    defaults: { _controller: AnhContentBundle:Admin:tagDelete }

anh_content_admin_paper_list:
    pattern: /{section}-list-{page}
    defaults: { _controller: AnhContentBundle:Admin:paperList, page: 1 }
    requirements:
        section: "[a-z\d]+"
        page: "\d+"

anh_content_admin_paper_add:
    pattern: /{section}-add
    defaults: { _controller: AnhContentBundle:Admin:paperAdd }
    requirements:
        section: "[a-z\d]+"

anh_content_admin_paper_edit:
    pattern: /edit-{id}
    defaults: { _controller: AnhContentBundle:Admin:paperEdit }
    requirements:
        id: "\d+"

anh_content_admin_paper_delete:
    pattern: /{section}-delete
    defaults: { _controller: AnhContentBundle:Admin:paperDelete }
    methods: [ 'POST' ]
    requirements:
        section: "[a-z\d]+"
