parameters:
    anh_content.entity.category.class: Anh\ContentBundle\Entity\Category
    anh_content.entity.paper.class: Anh\ContentBundle\Entity\Paper
    anh_content.form.type.category.class: Anh\ContentBundle\Form\CategoryType
    anh_content.form.type.paper.class: Anh\ContentBundle\Form\PaperType
    anh_content.bbcode_parser.class: Anh\ContentBundle\EventListener\BbcodeParser
    anh_content.uploader.class: Anh\ContentBundle\EventListener\Uploader
    anh_content.asset.manager.class: Anh\ContentBundle\AssetManager
    anh_content.asset.listener.class: Anh\ContentBundle\EventListener\AssetListener
    anh_content.asset.storage.class: Anh\ContentBundle\AssetUploaderStorage
    anh_content.url_generator.class: Anh\ContentBundle\UrlGenerator
    anh_content.url_generator.listener.class: Anh\ContentBundle\EventListener\UrlGenerator
    anh_content.twig.content_extension.class: Anh\ContentBundle\Twig\ContentExtension
    anh_content.section_is_configured.validator.class: Anh\ContentBundle\Validator\Constraints\SectionIsConfiguredValidator
    anh_content.category_is_required.validator.class: Anh\ContentBundle\Validator\Constraints\CategoryIsRequiredValidator
    anh_content.feed_data_provider.class: Anh\ContentBundle\FeedDataProvider
    anh_content.filter.admin_paper_list.class: Anh\ContentBundle\Filter\PaperFilter
    anh_content.filter.admin_category_list.class: Anh\ContentBundle\Filter\CategoryFilter

services:
    anh_content.bundle:
        class: Anh\ContentBundle\AnhContentBundle
        factory_service: kernel
        factory_method: getBundle
        arguments:
            - 'AnhContentBundle'
        tags:
            - { name: anh_admin.bundle }

    anh_content.form.type.category:
        class: %anh_content.form.type.category.class%
        arguments:
            - %anh_content.entity.category.class%
            - %anh_content.sections%
        tags:
            - { name: form.type, alias: anh_content_form_type_category }

    anh_content.form.type.paper:
        class: %anh_content.form.type.paper.class%
        arguments:
            - %anh_content.entity.paper.class%
            - %anh_content.entity.category.class%
            - %anh_content.sections%
            - @anh_taggable.manager
            - @oneup_uploader.templating.uploader_helper
        tags:
            - { name: form.type, alias: anh_content_form_type_paper }

    anh_content.asset.manager:
        class: %anh_content.asset.manager.class%
        arguments:
            - %anh_content.assets_dir%
            - @liip_imagine.cache.manager
            - %liip_imagine.filter_sets%

    anh_content.asset.remove_listener:
        class: %anh_content.asset.listener.class%
        arguments:
            - @anh_content.asset.manager
        tags:
            - { name: doctrine.event_subscriber }

    anh_content.asset.upload_listener:
        class: %anh_content.asset.listener.class%
        arguments:
            - @anh_content.asset.manager
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload.anh_content_assets, method: onUpload }

    anh_content.bbcode_parser:
        class: %anh_content.bbcode_parser.class%
        arguments:
            - %anh_content.sections%
            - @anh_content.url_generator
            - @anh_content.asset.manager
        tags:
            - { name: kernel.event_subscriber }

    anh_content.asset.storage:
        class: %anh_content.asset.storage.class%
        # class: %oneup_uploader.storage.filesystem.class%
        arguments:
            - %anh_content.assets_dir%

    anh_content.asset.data_loader:
        class: %liip_imagine.data.loader.filesystem.class%
        arguments:
            - @liip_imagine
            - %liip_imagine.formats%
            - %anh_content.assets_dir%
        tags:
            - { name: liip_imagine.data.loader, loader: anh_content_asset_data_loader }

    anh_content.url_generator:
        class: %anh_content.url_generator.class%
        arguments:
            - %anh_content.sections%
            - @router
            - @event_dispatcher

    anh_content.url_generator.listener:
        class: %anh_content.url_generator.listener.class%
        arguments:
            - %anh_content.sections%
        tags:
            - { name: kernel.event_subscriber }

    anh_content.twig.content_extension:
        class: %anh_content.twig.content_extension.class%
        arguments:
            - @anh_content.url_generator
            - @anh_content.asset.manager
            - %anh_content.sections%
        tags:
            - { name: twig.extension }

    anh_content.section_is_configured.validator:
        class: %anh_content.section_is_configured.validator.class%
        arguments:
            - %anh_content.sections%
        tags:
            - { name: validator.constraint_validator, alias: anh_content_section_is_configured_validator }

    anh_content.category_is_required.validator:
        class: %anh_content.category_is_required.validator.class%
        arguments:
            - %anh_content.sections%
        tags:
            - { name: validator.constraint_validator, alias: anh_content_category_is_required_validator }

    anh_content.filter.admin_paper_list:
        class: %anh_content.filter.admin_paper_list.class%
        arguments:
            - %anh_content.entity.category.class%
            - %anh_content.sections%

    anh_content.filter.admin_category_list:
        class: %anh_content.filter.admin_category_list.class%
        arguments:
            - %anh_content.sections%
