parameters:
    anh_content.entity.category.class: Anh\Bundle\ContentBundle\Entity\Category
    anh_content.entity.paper.class: Anh\Bundle\ContentBundle\Entity\Paper
    anh_content.manager.category.class: Anh\Bundle\ContentBundle\Entity\CategoryManager
    anh_content.manager.paper.class: Anh\Bundle\ContentBundle\Entity\PaperManager
    anh_content.form.type.category.class: Anh\Bundle\ContentBundle\Form\CategoryType
    anh_content.form.type.paper.class: Anh\Bundle\ContentBundle\Form\PaperType
    anh_content.bbcode_parser.class: Anh\Bundle\ContentBundle\EventListener\BbcodeParser
    anh_content.uploader.class: Anh\Bundle\ContentBundle\EventListener\Uploader
    anh_content.asset_remover.class: Anh\Bundle\ContentBundle\EventListener\AssetRemover
    anh_content.asset_manager.class: Anh\Bundle\ContentBundle\AssetManager

services:
    anh_content.bundle:
        class: Anh\Bundle\ContentBundle\AnhContentBundle
        factory_service: kernel
        factory_method: getBundle
        arguments:
            - 'AnhContentBundle'
        tags:
            - { name: anh_admin.bundle }

    anh_content.manager.category:
        class: %anh_content.manager.category.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %anh_content.entity.category.class%

    anh_content.manager.paper:
        class: %anh_content.manager.paper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %anh_content.entity.paper.class%
            - @anh_pager.pager
            - @anh_taggable.manager

    anh_content.form.type.category:
        class: %anh_content.form.type.category.class%
        arguments:
            - %anh_content.entity.category.class%
            - %anh_content.sections%
        tags:
            - { name: form.type, alias: anh_content_form_type_category }

    anh_content.form.type.paper:
        class: %anh_content.form.type.paper.class%
        arguments:
            - %anh_content.entity.paper.class%
            - %anh_content.entity.category.class%
            - %anh_content.sections%
            - @anh_taggable.manager
        tags:
            - { name: form.type, alias: anh_content_form_type_paper }

    anh_content.uploader:
        class: %anh_content.uploader.class%
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    anh_content.asset_remover:
        class: %anh_content.asset_remover.class%
        arguments:
            - @anh_content.asset_manager
        tags:
            - { name: doctrine.event_subscriber }

    anh_content.asset_manager:
        class: %anh_content.asset_manager.class%
        arguments:
            - %kernel.root_dir%

    anh_content.bbcode_parser:
        class: %anh_content.bbcode_parser.class%
        arguments:
            - %anh_content.sections%
            - @router
            - @anh_content.asset_manager
        tags:
            - { name: kernel.event_subscriber }
