parameters:
    anh_content.entity.category.class: Anh\ContentBundle\Entity\Category
    anh_content.entity.paper.class: Anh\ContentBundle\Entity\Paper
    anh_content.manager.category.class: Anh\ContentBundle\Entity\CategoryManager
    anh_content.manager.paper.class: Anh\ContentBundle\Entity\PaperManager
    anh_content.form.type.category.class: Anh\ContentBundle\Form\CategoryType
    anh_content.form.type.paper.class: Anh\ContentBundle\Form\PaperType
    anh_content.bbcode_parser.class: Anh\ContentBundle\EventListener\BbcodeParser
    anh_content.uploader.class: Anh\ContentBundle\EventListener\Uploader
    anh_content.asset.manager.class: Anh\ContentBundle\AssetManager
    anh_content.asset.listener.class: Anh\ContentBundle\EventListener\AssetListener
    anh_content.asset.storage.class: Anh\ContentBundle\AssetUploaderStorage
    anh_content.url_generator.class: Anh\ContentBundle\UrlGenerator

services:
    anh_content.bundle:
        class: Anh\ContentBundle\AnhContentBundle
        factory_service: kernel
        factory_method: getBundle
        arguments:
            - 'AnhContentBundle'
        tags:
            - { name: anh_admin.bundle }

    anh_content.manager.category:
        class: %anh_content.manager.category.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %anh_content.entity.category.class%

    anh_content.manager.paper:
        class: %anh_content.manager.paper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %anh_content.entity.paper.class%
            - @anh_pager.pager
            - @anh_taggable.manager

    anh_content.form.type.category:
        class: %anh_content.form.type.category.class%
        arguments:
            - %anh_content.entity.category.class%
            - %anh_content.sections%
        tags:
            - { name: form.type, alias: anh_content_form_type_category }

    anh_content.form.type.paper:
        class: %anh_content.form.type.paper.class%
        arguments:
            - %anh_content.entity.paper.class%
            - %anh_content.entity.category.class%
            - %anh_content.sections%
            - @anh_taggable.manager
        tags:
            - { name: form.type, alias: anh_content_form_type_paper }

    anh_content.asset.manager:
        class: %anh_content.asset.manager.class%
        arguments:
            - %anh_content.assets_dir%
            - @liip_imagine.cache.manager
            - %liip_imagine.filter_sets%

    anh_content.asset.remove_listener:
        class: %anh_content.asset.listener.class%
        arguments:
            - @anh_content.asset.manager
        tags:
            - { name: doctrine.event_subscriber }

    anh_content.asset.upload_listener:
        class: %anh_content.asset.listener.class%
        arguments:
            - @anh_content.asset.manager
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload.anh_content_assets, method: onUpload }

    anh_content.bbcode_parser:
        class: %anh_content.bbcode_parser.class%
        arguments:
            - %anh_content.sections%
            - @router
            - @anh_content.asset.manager
        tags:
            - { name: kernel.event_subscriber }

    anh_content.asset.storage:
        class: %anh_content.asset.storage.class%
        # class: %oneup_uploader.storage.filesystem.class%
        arguments:
            - %anh_content.assets_dir%

    anh_content.asset.data_loader:
        class: %liip_imagine.data.loader.filesystem.class%
        arguments:
            - @liip_imagine
            - %liip_imagine.formats%
            - %anh_content.assets_dir%
        tags:
            - { name: liip_imagine.data.loader, loader: anh_content_asset_data_loader }

    anh_content.url_generator:
        class: %anh_content.url_generator.class%
        arguments:
            - %anh_content.sections%
            - @router